version: '3.9'

services:
  svelte-kit:
    build:
      context: .
      dockerfile: ./docker/bun/Dockerfile
    volumes:
      - ./:/home/bun/ai-svelte-kit
    stdin_open: true
    tty: true
    restart: unless-stopped
    container_name: ai-svelte-kit
    ports:
      - 5173:5173
      - 4173:4173
